# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 11:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('email', models.EmailField(max_length=100, primary_key=True, serialize=False, verbose_name='Epost Adresse')),
                ('first_name', models.CharField(max_length=100, verbose_name='Fornavn')),
                ('last_name', models.CharField(max_length=100, verbose_name='Etternavn')),
                ('phone_number', models.CharField(max_length=12, verbose_name='Telefonnummer')),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Kunde', to='orderSchema.Customer', verbose_name='Kunde')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_name', models.CharField(max_length=255, verbose_name='Plane Navn')),
                ('size', models.CharField(max_length=100, verbose_name='St\xf8rrelse')),
                ('amount', models.IntegerField(default=0, verbose_name='Antall')),
                ('price', models.IntegerField(default=0, verbose_name='Pris (Per Plante)')),
                ('link', models.CharField(max_length=255, verbose_name='Lenke til plante')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orderSchema.Customer')),
            ],
        ),
    ]
