# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-28 18:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('orderSchema', '0002_auto_20171114_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Bestilligns dato'),
            preserve_default=False,
        ),
    ]
