# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 13:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orderSchema', '0004_auto_20171202_1221'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='misc_info',
            field=models.TextField(blank=True, null=True, verbose_name='Notat'),
        ),
        migrations.AlterField(
            model_name='product',
            name='amount',
            field=models.IntegerField(default=1, verbose_name='Antall'),
        ),
    ]
